name: next-leetcode-clone

services:
  postgres:
    image: postgres
    container_name: next-leetcode-clone-postgres
    environment:
      POSTGRES_DB: next-leetcode-clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - next-leetcode-clone_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  next-leetcode-clone_postgres_data:
